// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzFYhVCFcsdRGfLMw4p3gCJ45LKh7Qu7I',
    appId: '1:941894751722:web:f1d3e18d5cd5263fef0e93',
    messagingSenderId: '941894751722',
    projectId: 'student-expense-assistant',
    authDomain: 'student-expense-assistant.firebaseapp.com',
    storageBucket: 'student-expense-assistant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqEwoI3SSbbJAIL_h3bA5N7xK11ET8UU',
    appId: '1:941894751722:android:896987df40ece014ef0e93',
    messagingSenderId: '941894751722',
    projectId: 'student-expense-assistant',
    storageBucket: 'student-expense-assistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkPxvTZnHvHNIZI32TvrXd_HvMCEhEICg',
    appId: '1:941894751722:ios:8b90675a8a1921b2ef0e93',
    messagingSenderId: '941894751722',
    projectId: 'student-expense-assistant',
    storageBucket: 'student-expense-assistant.firebasestorage.app',
    iosBundleId: 'com.example.studentExpenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkPxvTZnHvHNIZI32TvrXd_HvMCEhEICg',
    appId: '1:941894751722:ios:8b90675a8a1921b2ef0e93',
    messagingSenderId: '941894751722',
    projectId: 'student-expense-assistant',
    storageBucket: 'student-expense-assistant.firebasestorage.app',
    iosBundleId: 'com.example.studentExpenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzFYhVCFcsdRGfLMw4p3gCJ45LKh7Qu7I',
    appId: '1:941894751722:web:78378ee1f3480ba1ef0e93',
    messagingSenderId: '941894751722',
    projectId: 'student-expense-assistant',
    authDomain: 'student-expense-assistant.firebaseapp.com',
    storageBucket: 'student-expense-assistant.firebasestorage.app',
  );
}
